#ifndef _KEYS_H
#define _KEYS_H

#define KEY_UP		0
#define KEY_DOWN	1
#define KEY_LEFT	2
#define KEY_RIGHT	3
#define KEY_SELECT	4
#define KEY_START	5
#define KEY_A		6
#define KEY_B		7

#define KEY_UP_PORT PORTD
#define KEY_DOWN_PORT PORTB
#define KEY_LEFT_PORT PORTD
#define KEY_RIGHT_PORT PORTC
#define KEY_SELECT_PORT PORTA
#define KEY_START_PORT PORTA
#define KEY_A_PORT PORTA
#define KEY_B_PORT PORTA

#define KEY_UP_PIN PIND
#define KEY_DOWN_PIN PINB
#define KEY_LEFT_PIN PIND
#define KEY_RIGHT_PIN PINC
#define KEY_SELECT_PIN PINA
#define KEY_START_PIN PINA
#define KEY_A_PIN PINA
#define KEY_B_PIN PINA

#define KEY_UP_DDR DDRD
#define KEY_DOWN_DDR DDRB
#define KEY_LEFT_DDR DDRD
#define KEY_RIGHT_DDR DDRC
#define KEY_SELECT_DDR DDRA
#define KEY_START_DDR DDRA
#define KEY_A_DDR DDRA
#define KEY_B_DDR DDRA

#define KEY_UP_PINN PORTD3
#define KEY_DOWN_PINN PORTB0
#define KEY_LEFT_PINN PORTD4
#define KEY_RIGHT_PINN PORTC4
#define KEY_SELECT_PINN PORTA3
#define KEY_START_PINN PORTA2
#define KEY_A_PINN PORTA0
#define KEY_B_PINN PORTA1


#define KEY_UP_PCMSK PCMSK3
#define KEY_DOWN_PCMSK PCMSK1
#define KEY_LEFT_PCMSK PCMSK3
#define KEY_RIGHT_PCMSK PCMSK2
#define KEY_SELECT_PCMSK PCMSK0
#define KEY_START_PCMSK PCMSK0
#define KEY_A_PCMSK PCMSK0
#define KEY_B_PCMSK PCMSK0


#define KEY_UP_PCINT PCINT27
#define KEY_DOWN_PCINT PCINT8
#define KEY_LEFT_PCINT PCINT28
#define KEY_RIGHT_PCINT PCINT20
#define KEY_SELECT_PCINT PCINT3
#define KEY_START_PCINT PCINT2
#define KEY_A_PCINT PCINT0
#define KEY_B_PCINT PCINT1



#endif

