#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/cu.usbserial-A100DEF4");
$port->databits(8);
$port->baudrate(500000);
$port->parity("none");
$port->stopbits(1);

while(1)
{

	setColor(100,0,0,0);
	usleep(1000000);

	setColor(0,100,0,0);
	usleep(1000000);

	setColor(0,0,100,0);
	usleep(1000000);

	setColor(0,0,0,100);
	usleep(1000000);

}
warn $port->read(1);

sub setColor($$$$)
{
	my $r = shift;
	my $g = shift;
	my $b = shift;
	my $w = shift;

	my $return=$port->write(chr(0x42).chr(0xFF).esc(chr($r).chr($g).chr($b).chr($w)));
	usleep(1000);
	
	$r = $r | ($w/3);
	$g = $g | ($w/3);
	$b = $b | ($w/3);
	
	my $return=$port->write(chr(0x42).chr(0).chr(0).esc(chr($r).chr($g).chr($b)));
	usleep(1000);
}



sub esc($)
{
    my $data = shift;
    
    
	$data =~ s/\x23/\x65\x1/go;
	$data =~ s/\x42/\x65\x2/go;
	$data =~ s/\x65/\x65\x3/go;
	$data =~ s/\x66/\x65\x4/go;
                                                            
	return $data;
}
