#!/usr/bin/perl

use strict;
use ceilingLight;
use Time::HiRes qw(usleep);


ceilingLight::init();


my $h = 0;


while(1)
{
	$h+=0.82;
	

	$h = 0 if $h >= 360;

	(my $r2,my $g2,my $b2) = ceilingLight::hsv2rgb($h,1,1);
	
	my $r1 = int($r2*155);
	my $g1 = int($g2*155);
	my $b1 = int($b2*155);

	my $sum = $r1+$g1+$b1;

	my $div = $sum / 155;


	$r1 /= $div;
	$g1 /= $div;
	$b1 /= $div;


	ceilingLight::setColor(0,$r1,$g1,$b1,0);
	

	usleep(2001);

}
warn ceilingLight::read();

