#!/usr/bin/perl

use strict;
use ceilingLight;
use Time::HiRes qw(usleep);


ceilingLight::init();
ceilingLight::setColor(0,0,0,0,0);


my $h = 0;


while(1)
{
	$h+=12.82;
	

	$h = 0 if $h >= 360;

	(my $r2,my $g2,my $b2) = ceilingLight::hsv2rgb($h,1,1);
	
	my $r1 = int($r2*255);
	my $g1 = int($g2*255);
	my $b1 = int($b2*255);

	my $sum = $r1+$g1+$b1;

	my $div = $sum / 255;


#	$r1 /= $div;
#	$g1 /= $div;
#	$b1 /= $div;


	ceilingLight::setColor(1,$r1,0,0,0);
	ceilingLight::setColor(2,0,$g1,0,0);
	ceilingLight::setColor(3,0,0,$b1,0);
	

	usleep(3001);

}
warn ceilingLight::read();

