#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/cu.usbserial-A100DEF4");
$port->databits(8);
$port->baudrate(115200);
$port->parity("none");
$port->stopbits(1);


while(1)
{
	my $return=$port->write(chr(0x23).chr(2).chr(255).chr(255).chr(255).chr(255));
	usleep(200000);
	my $return=$port->write(chr(0x23).chr(3).chr(255).chr(255).chr(255).chr(255));
	usleep(200000);
	my $return=$port->write(chr(0x23).chr(4).chr(255).chr(255).chr(255).chr(255));
	usleep(200000);
	my $return=$port->write(chr(0x23).chr(5).chr(255).chr(255).chr(255).chr(255));
	usleep(200000);
}
warn $port->read(1);
