#!/usr/bin/perl

use strict;
use ceilingLight;
use Time::HiRes qw(usleep);


ceilingLight::init();

while(1)
{

	ceilingLight::setColor(0,255,0,0,0);
	usleep(500000);
	ceilingLight::setColor(0,0,80,0,0);
	usleep(500000);
	ceilingLight::setColor(0,0,0,100,0);

	usleep(500000);

}
warn ceilingLight::read();

