#!/usr/bin/perl

use Device::SerialPort;
use Time::HiRes qw(usleep);

my $port = Device::SerialPort->new("/dev/cu.usbserial-A100DEF4");
$port->databits(8);
$port->baudrate(115200);
$port->parity("none");
$port->stopbits(1);

while(1)
{


	usleep(1125001);
	setColor(235,235,235,235);
	
	


}
warn $port->read(1);

sub setColor($$$$)
{
	my $r = shift;
	my $g = shift;
	my $b = shift;
	my $w = shift;

	my $return=$port->write(chr(0x23).esc(chr(2).chr($r).chr($g).chr($b).chr($w)));
	usleep(1000);
	my $return=$port->write(chr(0x23).esc(chr(3).chr($r).chr($g).chr($b).chr($w)));
	usleep(1000);
	my $return=$port->write(chr(0x23).esc(chr(4).chr($r).chr($g).chr($b).chr($w)));
	usleep(1000);
	my $return=$port->write(chr(0x23).esc(chr(5).chr($r).chr($g).chr($b).chr($w)));
	usleep(1000);
}



sub esc($)
{
    my $data = shift;
    
    
    $data =~ s/\x42/\x42\x2/go;
	$data =~ s/\x23/\x42\x1/go;
                                                            
	return $data;
}
